### ISSUE TITLE
Ajout images dans les légumes

### ISSUE THREAD

**Issue by IsaBartkowiak** [IsaBartkowiak/fermedavenir#17]

**Comment by Michaelvilleneuve** [comment]
En fait on va pas mettre un upload d'image pour les légumes et une gestion avec amazon S3, on va juste mettre un dossier legumes dans les assets images, et on va mettre le plus de photos de legumes quon peut en les nommant "radis", ou "patate" et si le nom du legume est le meme on l'affiche, sinon on met un placeholder
