### ISSUE TITLE
Style panier (liste des paniers)

### ISSUE THREAD

**Issue by IsaBartkowiak** [IsaBartkowiak/fermedavenir#4]
Reprendre la maquette
<img width="1045" alt="capture d ecran 2016-03-16 a 10 32 36" src="https://cloud.githubusercontent.com/assets/9010004/13807651/759d24c0-eb62-11e5-9c4c-ef28464fbc06.png">

**Comment by FredericBriolet** [comment]
+ styler la vue "Overview" (réduire l'épaisseur des bordures)
<img width="1034" alt="capture d ecran 2016-03-17 a 10 09 34" src="https://cloud.githubusercontent.com/assets/6231384/13841309/66ae1d86-ec28-11e5-90a9-ff5fc0200e82.png">

**Comment by FredericBriolet** [comment]
Presque close, style sidebar
