### ISSUE TITLE
La BDD est entièrement en anglais

### ISSUE THREAD

**Issue by korasaccharin** [IsaBartkowiak/fermedavenir#42]
Actuellement, le projet a des tables telles que "panier" ou "legume". La table "legume" contient des champs "variete" et "caracteristique".

**Comment by Michaelvilleneuve** [comment]
Ça manque de cohérence oui mais on a fait ça car beaucoup de termes nous paraissaient trop techniques ex: 'parcelles', etc, faudrait définir un bon lexique en anglais de tous les termes liés aux fermes

**Comment by korasaccharin** [comment]
D'accord. Je propose les changements suivants :

Farm
 - name
 - slug
 - location
 - tutorial
 - lat -> latitude
 - lng -> longitude

Parcelle -> Plot
 - location
 - title -> name

Panier -> Basket ou Hamper
 - semaine -> week
 - quantity

User
 - email
 - password
 - statut -> status (mais ne s'agit-il pas plutôt d'un rôle ?)

Legume -> Vegetable
 - title -> name
 - variete -> type
 - caracteristique -> feature
 - nb_per_kilo
 - price

Generation
 - semi_from -> seedling_from (il s'agit bien du "semis" français avec une faute d'orthographe ? parce que le "semi" anglais est l'abréviation de semiconducteur) 
 - semi_to ->seedling_to (même question)
 - recolte -> harvest
 - conservation_to -> preservation_until / preservation_during / available_for

Aucun changement sur Plantation et Portion.

**Comment by arnaudlevy** [comment]
Vegetable ne recouvre pas Fruit, je pense que Green est une option

**Comment by arnaudlevy** [comment]
Ou alors Plant

**Comment by Michaelvilleneuve** [comment]
Plant c'est pas mal vu qu'il y a des "plantations", c'est cohérent, et ça parle plus que green je pense
