### ISSUE TITLE
Quelqu'un peut m'expliquer la différence entre une génération et un plantation ?

### ISSUE THREAD

**Issue by ghost** [IsaBartkowiak/fermedavenir#51]

**Comment by IsaBartkowiak** [comment]
Une génération correspond à une période de semis, plantation, récolte dans l'année, c'est une possibilité de plantation. Ex: radis de février, de juin, de novembre. Une plantation correspond a une generation plantée avec une quantité. Les générations sont les memes pour toutes les annees tandis que les plantations ne sont valables que sur une année. Je ne sais pas je suis très claire mais c'est ce que j'ai compris :)

**Comment by ghost** [comment]
L'application m'organise mon prévisionnel lorsque j'organise mes paniers. À quoi servent les générations ? Je ne comprends pas la différence… Merci :)

**Comment by ghost** [comment]
Après discussion avec Arnaud, le problème vient de la confusion entre la base de légumes publique, partagée par tous les utilisateurs du site, et les plantations spécifiques à une ferme.
